import { translations } from '@/i18n/translations';

export interface DocumentationSection {
  title: string;
  content: string[];
}

export interface DocumentationStructure {
  title: string;
  subtitle: string;
  sections: DocumentationSection[];
  appendix: {
    title: string;
    content: string[];
  };
}

/**
 * Get the complete documentation structure with Portuguese institutional content
 */
export function getDocumentationContent(): DocumentationStructure {
  const pt = translations.pt;

  return {
    title: 'AntiFraud',
    subtitle: 'by HCoragem',
    sections: [
      {
        title: '1. Branding',
        content: [
          'Nome do Produto: AntiFraud',
          'Subtítulo: by HCoragem',
          '',
          'Todos os referenciais e ligações no sistema devem exibir exclusivamente a nomenclatura oficial "AntiFraud".',
          'O subtítulo "by HCoragem" deve aparecer consistentemente em rodapés e áreas de branding secundário.',
          'Esta nomenclatura assegura consistência total no branding e reforça a identidade do produto.',
        ],
      },
      {
        title: '2. Páginas Institucionais',
        content: [
          '=== MISSÃO ===',
          '',
          pt.missionPageHeading,
          pt.missionPageSubheading,
          '',
          pt.missionVisionTitle,
          ...pt.missionVisionParagraphs,
          '',
          pt.missionCoreTitle,
          ...pt.missionCoreParagraphs,
          '',
          pt.missionImpactTitle,
          ...pt.missionImpactParagraphs,
          '',
          pt.missionValuesTitle,
          ...pt.missionValuesParagraphs,
          '',
          pt.missionLimitationsTitle,
          ...pt.missionLimitationsParagraphs,
          '',
          pt.missionResponsibleUseTitle,
          ...pt.missionResponsibleUseParagraphs,
          '',
          '=== COMO FUNCIONA ===',
          '',
          pt.howItWorksPageHeading,
          pt.howItWorksPageSubheading,
          '',
          pt.howItWorksIntroTitle,
          ...pt.howItWorksIntroParagraphs,
          '',
          pt.howItWorksEmailTitle,
          ...pt.howItWorksEmailParagraphs,
          '',
          pt.howItWorksPhoneTitle,
          ...pt.howItWorksPhoneParagraphs,
          '',
          pt.howItWorksMessageTitle,
          ...pt.howItWorksMessageParagraphs,
          '',
          pt.howItWorksCryptoTitle,
          ...pt.howItWorksCryptoParagraphs,
          '',
          pt.howItWorksScoringTitle,
          ...pt.howItWorksScoringParagraphs,
          '',
          pt.howItWorksLimitationsTitle,
          ...pt.howItWorksLimitationsParagraphs,
          '',
          pt.howItWorksResponsibleUseTitle,
          ...pt.howItWorksResponsibleUseParagraphs,
          '',
          '=== TERMOS E CONDIÇÕES ===',
          '',
          pt.termsPageHeading,
          pt.termsPageSubheading,
          '',
          ...pt.termsSection1Paragraphs.map((p: string) => `${pt.termsSection1Title}: ${p}`),
          '',
          ...pt.termsSection2Paragraphs.map((p: string) => `${pt.termsSection2Title}: ${p}`),
          '',
          ...pt.termsSection3Paragraphs.map((p: string) => `${pt.termsSection3Title}: ${p}`),
          '',
          ...pt.termsSection4Paragraphs.map((p: string) => `${pt.termsSection4Title}: ${p}`),
          '',
          ...pt.termsSection5Paragraphs.map((p: string) => `${pt.termsSection5Title}: ${p}`),
          '',
          ...pt.termsSection6Paragraphs.map((p: string) => `${pt.termsSection6Title}: ${p}`),
          '',
          ...pt.termsSection7Paragraphs.map((p: string) => `${pt.termsSection7Title}: ${p}`),
          '',
          ...pt.termsSection8Paragraphs.map((p: string) => `${pt.termsSection8Title}: ${p}`),
          '',
          '=== POLÍTICA DE PRIVACIDADE ===',
          '',
          pt.privacyPageHeading,
          pt.privacyPageSubheading,
          '',
          ...pt.privacySection1Paragraphs.map((p: string) => `${pt.privacySection1Title}: ${p}`),
          '',
          ...pt.privacySection2Paragraphs.map((p: string) => `${pt.privacySection2Title}: ${p}`),
          '',
          ...pt.privacySection3Paragraphs.map((p: string) => `${pt.privacySection3Title}: ${p}`),
          '',
          ...pt.privacySection4Paragraphs.map((p: string) => `${pt.privacySection4Title}: ${p}`),
          '',
          ...pt.privacySection5Paragraphs.map((p: string) => `${pt.privacySection5Title}: ${p}`),
          '',
          ...pt.privacySection6Paragraphs.map((p: string) => `${pt.privacySection6Title}: ${p}`),
          '',
          ...pt.privacySection7Paragraphs.map((p: string) => `${pt.privacySection7Title}: ${p}`),
          '',
          ...pt.privacySection8Paragraphs.map((p: string) => `${pt.privacySection8Title}: ${p}`),
        ],
      },
      {
        title: '3. Motor Antifraude (100% Frontend)',
        content: [
          'O AntiFraud implementa um motor de análise heurística 100% frontend, sem dependências de servidor.',
          '',
          'Características principais:',
          '• Análise offline de mensagens, emails, telefones e endereços de criptomoeda',
          '• Heurísticas determinísticas baseadas em padrões conhecidos de fraude',
          '• Idioma único por sessão (sem mistura de PT/EN na mesma análise)',
          '• Palavras-chave críticas disparam automaticamente Risco Alto',
          '',
          'Palavras-chave críticas que disparam Risco Alto:',
          '• dinheiro, lucro, promoção, oportunidade, grátis',
          '• encontros, investimento, criptomoeda',
          '',
          'Estrutura de resultado:',
          '• Nível de Risco: Baixo / Médio / Elevado',
          '• Explicação: Descrição dos indicadores encontrados',
          '• Recomendação: Ação sugerida ao utilizador',
          '',
          'Todas as análises são realizadas localmente no navegador, garantindo privacidade total.',
        ],
      },
      {
        title: '4. PWA (Progressive Web App)',
        content: [
          'O AntiFraud é uma aplicação web progressiva totalmente instalável.',
          '',
          'Funcionalidades PWA:',
          '• Instalação em Android, iOS e Desktop',
          '• Funcionamento offline após primeira carga',
          '• Ícones e manifest configurados',
          '• Service Worker para cache inteligente',
          '',
          'CTA de Instalação:',
          '• Texto: "Baixe a Aplicação AntiFraud gratuitamente"',
          '• Traduzido em todos os idiomas suportados',
          '• Visível quando a aplicação é instalável',
          '',
          'A instalação permite acesso rápido e experiência nativa em qualquer dispositivo.',
        ],
      },
      {
        title: '5. Modal de Cookies e Termos',
        content: [
          'Modal obrigatória que bloqueia a UI até aceitação do utilizador.',
          '',
          'Requisitos de aceitação:',
          '• Uso mínimo de cookies (checkbox obrigatório)',
          '• Termos & Condições (checkbox obrigatório)',
          '• Política de Privacidade (checkbox obrigatório)',
          '',
          'Comportamento:',
          '• Bloqueia toda a interação até aceitação',
          '• Links in-modal para /terms e /privacy',
          '• Previne fecho com ESC ou clique fora',
          '• Traduzida em todos os idiomas suportados',
          '',
          'A modal garante conformidade legal e transparência no uso de dados.',
        ],
      },
      {
        title: '6. Navegação e Aliases de Rotas',
        content: [
          'Rotas principais:',
          '• / (home)',
          '• /mission',
          '• /how-it-works',
          '• /terms',
          '• /privacy',
          '• /documentation',
          '',
          'Aliases legados (redirecionam para rotas canónicas):',
          '• /institucional → /mission',
          '• /institucional/mission → /mission',
          '',
          'Todas as rotas são geridas client-side com fallback 404.html para deep links.',
          'A navegação é consistente e estável em toda a aplicação.',
        ],
      },
      {
        title: '7. Checklist de Verificação Final',
        content: [
          '✓ Branding: "AntiFraud" + "by HCoragem" consistente',
          '✓ Páginas institucionais completas em PT',
          '✓ Traduções multilíngues (EN/ES/FR/ZH/AR/RU)',
          '✓ Motor antifraude 100% frontend funcional',
          '✓ Palavras críticas disparam Risco Alto',
          '✓ PWA instalável em todos os dispositivos',
          '✓ CTA de instalação traduzido',
          '✓ Modal de cookies/termos obrigatória',
          '✓ Navegação e aliases funcionais',
          '✓ Sem resíduos de projetos antigos',
          '',
          'Todos os componentes foram testados e validados para garantir',
          'uma experiência consistente e profissional em todos os idiomas e dispositivos.',
        ],
      },
    ],
    appendix: {
      title: 'Apêndice: Idiomas Suportados',
      content: [
        'O AntiFraud suporta os seguintes idiomas na interface do utilizador:',
        '',
        '• Português (PT) - Idioma oficial e fonte de todas as traduções',
        '• Inglês (EN)',
        '• Espanhol (ES)',
        '• Francês (FR)',
        '• Chinês (ZH)',
        '• Árabe (AR)',
        '• Russo (RU)',
        '',
        'Todas as traduções são derivadas do conteúdo oficial em Português.',
        'O conteúdo institucional e legal mantém-se em Português como referência canónica.',
      ],
    },
  };
}
