import { Language } from '@/i18n/translations';

// Simple dictionary-based translation for common Portuguese scam analysis terms
const translationDictionary: Record<Language, Record<string, string>> = {
  pt: {},
  en: {
    'Risco': 'Risk',
    'ALTO': 'HIGH',
    'MÉDIO': 'MEDIUM',
    'BAIXO': 'LOW',
    'Análise': 'Analysis',
    'Esta mensagem': 'This message',
    'contém': 'contains',
    'indicadores': 'indicators',
    'de fraude': 'of fraud',
    'golpe': 'scam',
    'suspeita': 'suspicious',
    'urgência': 'urgency',
    'prêmio': 'prize',
    'ganhou': 'won',
    'clique': 'click',
    'link': 'link',
    'dados pessoais': 'personal data',
    'senha': 'password',
    'conta bancária': 'bank account',
    'transferência': 'transfer',
    'dinheiro': 'money',
    'pagamento': 'payment',
    'imediato': 'immediate',
    'urgente': 'urgent',
    'atenção': 'attention',
    'cuidado': 'caution',
    'Pontuação': 'Score',
    'pontos': 'points',
    'Recomendação': 'Recommendation',
    'Não': 'Do not',
    'não': 'do not',
    'responda': 'respond',
    'clique em links': 'click on links',
    'forneça informações': 'provide information',
    'segura': 'safe',
    'parece': 'appears',
    'legítima': 'legitimate',
  },
  es: {
    'Risco': 'Riesgo',
    'ALTO': 'ALTO',
    'MÉDIO': 'MEDIO',
    'BAIXO': 'BAJO',
    'Análise': 'Análisis',
    'Esta mensagem': 'Este mensaje',
    'contém': 'contiene',
    'indicadores': 'indicadores',
    'de fraude': 'de fraude',
    'golpe': 'estafa',
    'suspeita': 'sospechoso',
    'urgência': 'urgencia',
    'prêmio': 'premio',
    'ganhou': 'ganó',
    'clique': 'haga clic',
    'link': 'enlace',
    'dados pessoais': 'datos personales',
    'senha': 'contraseña',
    'conta bancária': 'cuenta bancaria',
    'transferência': 'transferencia',
    'dinheiro': 'dinero',
    'pagamento': 'pago',
    'imediato': 'inmediato',
    'urgente': 'urgente',
    'atenção': 'atención',
    'cuidado': 'cuidado',
    'Pontuação': 'Puntuación',
    'pontos': 'puntos',
    'Recomendação': 'Recomendación',
    'Não': 'No',
    'não': 'no',
    'responda': 'responda',
    'clique em links': 'haga clic en enlaces',
    'forneça informações': 'proporcione información',
    'segura': 'seguro',
    'parece': 'parece',
    'legítima': 'legítimo',
  },
  fr: {
    'Risco': 'Risque',
    'ALTO': 'ÉLEVÉ',
    'MÉDIO': 'MOYEN',
    'BAIXO': 'FAIBLE',
    'Análise': 'Analyse',
    'Esta mensagem': 'Ce message',
    'contém': 'contient',
    'indicadores': 'indicateurs',
    'de fraude': 'de fraude',
    'golpe': 'arnaque',
    'suspeita': 'suspect',
    'urgência': 'urgence',
    'prêmio': 'prix',
    'ganhou': 'gagné',
    'clique': 'cliquez',
    'link': 'lien',
    'dados pessoais': 'données personnelles',
    'senha': 'mot de passe',
    'conta bancária': 'compte bancaire',
    'transferência': 'transfert',
    'dinheiro': 'argent',
    'pagamento': 'paiement',
    'imediato': 'immédiat',
    'urgente': 'urgent',
    'atenção': 'attention',
    'cuidado': 'prudence',
    'Pontuação': 'Score',
    'pontos': 'points',
    'Recomendação': 'Recommandation',
    'Não': 'Ne',
    'não': 'ne',
    'responda': 'répondez',
    'clique em links': 'cliquez sur les liens',
    'forneça informações': 'fournissez des informations',
    'segura': 'sûr',
    'parece': 'semble',
    'legítima': 'légitime',
  },
  zh: {
    'Risco': '风险',
    'ALTO': '高',
    'MÉDIO': '中',
    'BAIXO': '低',
    'Análise': '分析',
    'Esta mensagem': '此消息',
    'contém': '包含',
    'indicadores': '指标',
    'de fraude': '欺诈',
    'golpe': '诈骗',
    'suspeita': '可疑',
    'urgência': '紧急',
    'prêmio': '奖品',
    'ganhou': '赢得',
    'clique': '点击',
    'link': '链接',
    'dados pessoais': '个人数据',
    'senha': '密码',
    'conta bancária': '银行账户',
    'transferência': '转账',
    'dinheiro': '钱',
    'pagamento': '付款',
    'imediato': '立即',
    'urgente': '紧急',
    'atenção': '注意',
    'cuidado': '小心',
    'Pontuação': '评分',
    'pontos': '分',
    'Recomendação': '建议',
    'Não': '不要',
    'não': '不要',
    'responda': '回复',
    'clique em links': '点击链接',
    'forneça informações': '提供信息',
    'segura': '安全',
    'parece': '似乎',
    'legítima': '合法',
  },
  ar: {
    'Risco': 'خطر',
    'ALTO': 'عالي',
    'MÉDIO': 'متوسط',
    'BAIXO': 'منخفض',
    'Análise': 'تحليل',
    'Esta mensagem': 'هذه الرسالة',
    'contém': 'تحتوي',
    'indicadores': 'مؤشرات',
    'de fraude': 'احتيال',
    'golpe': 'عملية احتيال',
    'suspeita': 'مشبوه',
    'urgência': 'عاجل',
    'prêmio': 'جائزة',
    'ganhou': 'فاز',
    'clique': 'انقر',
    'link': 'رابط',
    'dados pessoais': 'بيانات شخصية',
    'senha': 'كلمة المرور',
    'conta bancária': 'حساب بنكي',
    'transferência': 'تحويل',
    'dinheiro': 'مال',
    'pagamento': 'دفع',
    'imediato': 'فوري',
    'urgente': 'عاجل',
    'atenção': 'انتباه',
    'cuidado': 'حذر',
    'Pontuação': 'نقاط',
    'pontos': 'نقاط',
    'Recomendação': 'توصية',
    'Não': 'لا',
    'não': 'لا',
    'responda': 'ترد',
    'clique em links': 'انقر على الروابط',
    'forneça informações': 'تقدم معلومات',
    'segura': 'آمن',
    'parece': 'يبدو',
    'legítima': 'شرعي',
  },
  ru: {
    'Risco': 'Риск',
    'ALTO': 'ВЫСОКИЙ',
    'MÉDIO': 'СРЕДНИЙ',
    'BAIXO': 'НИЗКИЙ',
    'Análise': 'Анализ',
    'Esta mensagem': 'Это сообщение',
    'contém': 'содержит',
    'indicadores': 'индикаторы',
    'de fraude': 'мошенничества',
    'golpe': 'афера',
    'suspeita': 'подозрительный',
    'urgência': 'срочность',
    'prêmio': 'приз',
    'ganhou': 'выиграл',
    'clique': 'нажмите',
    'link': 'ссылка',
    'dados pessoais': 'личные данные',
    'senha': 'пароль',
    'conta bancária': 'банковский счет',
    'transferência': 'перевод',
    'dinheiro': 'деньги',
    'pagamento': 'платеж',
    'imediato': 'немедленный',
    'urgente': 'срочный',
    'atenção': 'внимание',
    'cuidado': 'осторожность',
    'Pontuação': 'Оценка',
    'pontos': 'баллов',
    'Recomendação': 'Рекомендация',
    'Não': 'Не',
    'não': 'не',
    'responda': 'отвечайте',
    'clique em links': 'нажимайте на ссылки',
    'forneça informações': 'предоставляйте информацию',
    'segura': 'безопасно',
    'parece': 'кажется',
    'legítima': 'законный',
  },
};

export function translateBackendResult(originalText: string, targetLanguage: Language): string {
  if (targetLanguage === 'pt' || !originalText) {
    return originalText;
  }

  const dictionary = translationDictionary[targetLanguage];
  if (!dictionary) {
    return originalText;
  }

  let translatedText = originalText;

  // Sort by length (longest first) to avoid partial replacements
  const sortedKeys = Object.keys(dictionary).sort((a, b) => b.length - a.length);

  for (const key of sortedKeys) {
    const regex = new RegExp(key, 'gi');
    translatedText = translatedText.replace(regex, dictionary[key]);
  }

  return translatedText;
}
